singleton Material("etki.skin.rennen")
{
    mapTo = "etki.skin.rennen";
    overlayMap[2] = "vehicles/etki/dpmp_skins/dpmp_rennen_skin/etki_skin_rennen.dds";
    diffuseMap[2] = "vehicles/etki/etki_c.dds";
    specularMap[2] = "vehicles/etki/etki_s.dds";
    normalMap[2] = "vehicles/etki/etki_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_d.dds";
    specularMap[1] = "vehicles/etki/etki_s.dds";
    normalMap[1] = "vehicles/etki/etki_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/etki/etki_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material("etki_modparts.skin.rennen")
{
    mapTo = "etki_modparts.skin.rennen";
    overlayMap[2] = "vehicles/etki/dpmp_skins/dpmp_rennen_skin/etki_skin_rennen.dds";
    diffuseMap[2] = "vehicles/etki/etki_modparts_c.dds";
    specularMap[2] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[2] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[1] = "vehicles/etki/etki_modparts_d.dds";
    specularMap[1] = "vehicles/etki/etki_modparts_s.dds";
    normalMap[1] = "vehicles/etki/etki_modparts_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/etki/etki_modparts_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};