singleton Material(brastowdpmp_engine)
{
    mapTo = "brastowdpmp_engine";
    diffuseMap[1] = "vehicles/miramar/miramar_engine_d.dds";
    specularMap[1] = "vehicles/miramar/miramar_engine_s.dds";
    normalMap[1] = "vehicles/miramar/miramar_engine_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/miramar/miramar_engine_n.dds";
    specularPower[0] = "32";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    diffuseColor[1] = "1 1 1 1";
    dynamicCubemap = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};

singleton Material(miramar)
{
    mapTo = "miramar";
    colorPaletteMap[3] = "vehicles/miramar/miramar_skin_chrome.dds";
    diffuseMap[3] = "vehicles/miramar/miramar_chrome.dds";
    specularMap[3] = "vehicles/miramar/miramar_s.dds";
    normalMap[3] = "vehicles/miramar/miramar_n.dds";
    specularPower[3] = "128";
    pixelSpecular[3] = "1";
    useAnisotropic[3] = "1";
    colorPaletteMap[2] = "vehicles/miramar/miramar_roof.dds";
    diffuseMap[2] = "vehicles/miramar/miramar_c.dds";
    specularMap[2] = "vehicles/miramar/miramar_s.dds";
    normalMap[2] = "vehicles/miramar/miramar_n.dds";
    diffuseMap[1] = "vehicles/miramar/miramar_d.dds";
    specularMap[1] = "vehicles/miramar/miramar_s.dds";
    normalMap[1] = "vehicles/miramar/miramar_n.dds";
    diffuseMap[0] = "vehicles/common/null.dds";
    specularMap[0] = "vehicles/common/null.dds";
    normalMap[0] = "vehicles/miramar/miramar_n.dds";
    specularPower[0] = "128";
    pixelSpecular[0] = "1";
    specularPower[1] = "32";
    pixelSpecular[1] = "1";
    specularPower[2] = "128";
    pixelSpecular[2] = "1";
    specularColor[0] = "1 1 1 1";
    specularColor[1] = "1 1 1 1";
    specularColor[2] = "1 1 1 1";
    diffuseColor[0] = "1 1 1 1";
    diffuseColor[1] = "1 1 1 1";
    diffuseColor[2] = "1 1 1 1";
    useAnisotropic[0] = "1";
    useAnisotropic[1] = "1";
    useAnisotropic[2] = "1";
    castShadows = "1";
    translucent = "1";
    translucentBlendOp = "None";
    alphaTest = "0";
    alphaRef = "0";
    dynamicCubemap = true;
    instanceDiffuse[2] = true;
    materialTag0 = "beamng"; materialTag1 = "vehicle";
};